erDiagram
    USER{
        str id "ID / primary key"
        str name "Name of user/agent"
        str description "Description of user / agent"
    }
    STATUS{
        str id "ID / primary key"
        str name "Short name for the status"
        str description "Description of the status"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str _comments "Free text comments on this record, for example description of changes made etc"
    }
    STATUS }o--||USER: "Record modified by"
    APPLICATION_AREA{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation for the application area."
        str description "Description of the application area."
        dict links "Link(s) to further information on the application area."
        int _version "Version of this record, e.g. 1."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    CLIMATE_ZONE{
        str id "ID / primary key."
        str inSchema "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation for the climate zone."
        str description "Description of the climate zone"
        dict links "Links providing further definition of climate zone"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str _comments "Free text comments on this record, for example description of changes made etc"
    }
    EXPOSURE{
        str id "ID / primary key."
        str inSchema "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation for exposure classification."
        str description "Description of sensor exposure according to WMO-No. 8."
        dict links "Links providing further definition of exposure class."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    FACILITY_TYPE{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation for the facility type."
        str description "Description of the facility type."
        dict links "Link(s) to definition of facility type."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    FEATURE_TYPE{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation for the feature type."
        str description "Description of the feature type."
        dict links "Link(s) to definition of feature type."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    MEASUREMENT_QUALITY{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation for the measurement quality classification."
        str description "Description of the measurement quality classification."
        dict links "Link(s) to definition of fmeasurement quality classification."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    MEDIA_TYPE{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation for the media type."
        str description "Description of the media type."
        dict links "Link(s) to definition of media type."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    OBSERVATION_TYPE{
        str id "ID / primary key"
        str inSchema "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation for the observation type."
        str description "Description of the observation type."
        dict links "Link(s) to definition of the observation type."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    OBSERVED_PROPERTY{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation of observed property, e.g. 'at' for air temperature."
        str description "Description of observed property."
        str standard_name "CF standard name (if applicable), e.g. 'air_temperature'."
        str units "Canonical units, e.g. 'Kelvin'."
        dict links "Link(s) to definition / source of observed property."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    OBSERVING_METHOD{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation of the observing method."
        str description "Description of observing method."
        dict links "Links providing further definition of observing method."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    OBSERVING_PROCEDURE{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation of the observing procedure."
        str description "Description of observing procedure."
        dict links "Links providing further definition of observing procedure."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    OBSERVING_PROGRAM{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation of the observing program."
        str description "Description of observing program."
        dict links "Links providing further definition of observing program."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    OPERATING_STATUS{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation of the operating status."
        str description "Description of operating status."
        dict links "Links providing further definition of operating status."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    REFERENCE_SURFACE{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation of the reference surface."
        str description "Description of reference surface."
        dict links "Links providing further definition of reference."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    REPRESENTATIVENESS{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation for the representativeness classification."
        str description "Description of the representativeness classification."
        dict links "Links providing further information on the representativeness classification."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    ROLE{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation of the role."
        str description "Description of the role."
        dict links "Links providing further information on the role."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    SOURCE_TYPE{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Name of source type"
        str description "Description of source type, e.g. file etc"
        str IANA_scheme "IANA scheme (if applicable)"
        str links "Links providing further definition of source type"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str _comments "Free text comments on this record, for example description of changes made etc"
    }
    SURFACE_COVER{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation of the surface cover classification."
        str description "Description of the surface cover classification."
        dict links "Links providing further information on the surface cover classification."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    SURFACE_ROUGHNESS{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation of the surface roughness classification."
        str description "Description of the surface roughness classification."
        dict links "Links providing further information on the surface roughness classification."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    TERRITORY{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation for the territory."
        str description "Official name of territory."
        str ISO3c "ISO 3 character country code."
        dict links "Link(s) to further information."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    TIME_ZONE{
        str id "ID / primary key"
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Name / abbreviation of time zone"
        str description "Description of the time zone."
        float offset "Offset from UTC in hours (decimal)"
        dict links "Link(s) to further information."
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str _comments "Free text comments on this record, for example description of changes made etc"
    }
    TOPOGRAPHY_BATHYMETRY{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation of the topography / bathymetry classification."
        str description "Description of the topography / bathymetry classification."
        dict links "Links providing further information on the topography / bathymetry classification."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    WMO_REGION{
        str id "ID / primary key."
        str inScheme "The scheme/vocabulary that this record is from."
        str name "Short name / abbreviation of the WMO regional association."
        str description "Description of the WMO regional association."
        dict links "Links providing further information on the WMO regional association."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    APPLICATION_AREA }o--||USER: "Record modified by"
    APPLICATION_AREA }o--||STATUS: "Record has status"
    CLIMATE_ZONE }o--||USER: "Record modified by"
    CLIMATE_ZONE }o--||STATUS: "Record has status"
    EXPOSURE }o--||USER: "Record modified by"
    EXPOSURE }o--||STATUS: "Record has status"
    FACILITY_TYPE }o--||USER: "Record modified by"
    FACILITY_TYPE }o--||STATUS: "Record has status"
    FEATURE_TYPE }o--||USER: "Record modified by"
    FEATURE_TYPE }o--||STATUS: "Record has status"
    MEASUREMENT_QUALITY }o--||USER: "Record modified by"
    MEASUREMENT_QUALITY }o--||STATUS: "Record has status"
    MEDIA_TYPE }o--||USER: "Record modified by"
    MEDIA_TYPE }o--||STATUS: "Record has status"
    OBSERVATION_TYPE }o--||USER: "Record modified by"
    OBSERVATION_TYPE }o--||STATUS: "Record has status"
    OBSERVED_PROPERTY }o--||USER: "Record modified by"
    OBSERVED_PROPERTY }o--||STATUS: "Record has status"
    OBSERVING_METHOD }o--||USER: "Record modified by"
    OBSERVING_METHOD }o--||STATUS: "Record has status"
    OBSERVING_PROCEDURE }o--||USER: "Record modified by"
    OBSERVING_PROCEDURE }o--||STATUS: "Record has status"
    OBSERVING_PROGRAM }o--||USER: "Record modified by"
    OBSERVING_PROGRAM }o--||STATUS: "Record has status"
    OPERATING_STATUS }o--||USER: "Record modified by"
    OPERATING_STATUS }o--||STATUS: "Record has status"
    REFERENCE_SURFACE }o--||USER: "Record modified by"
    REFERENCE_SURFACE }o--||STATUS: "Record has status"
    REPRESENTATIVENESS }o--||USER: "Record modified by"
    REPRESENTATIVENESS }o--||STATUS: "Record has status"
    ROLE }o--||USER: "Record modified by"
    ROLE }o--||STATUS: "Record has status"
    SOURCE_TYPE }o--||USER: "Record modified by"
    SOURCE_TYPE }o--||STATUS: "Record has status"
    SURFACE_COVER }o--||USER: "Record modified by"
    SURFACE_COVER }o--||STATUS: "Record has status"
    SURFACE_ROUGHNESS }o--||USER: "Record modified by"
    SURFACE_ROUGHNESS }o--||STATUS: "Record has status"
    TERRITORY }o--o|WMO_REGION: ""
    TERRITORY }o--||USER: "Record modified by"
    TERRITORY }o--||STATUS: "Record has status"
    TIME_ZONE }o--||USER: "Record modified by"
    TIME_ZONE }o--||STATUS: "Record has status"
    TOPOGRAPHY_BATHYMETRY }o--||USER: "Record modified by"
    TOPOGRAPHY_BATHYMETRY }o--||STATUS: "Record has status"
    WMO_REGION }o--||USER: "Record modified by"
    WMO_REGION }o--||STATUS: "Record has status"
    DEPLOYMENT{
        str id "Unique ID / primary key for deployment."
        float height_above_local_reference_surface "Installation height of equipment above reference surface (in meters)."
        datetime valid_from "Date that this record is valid from."
        datetime valid_to "Date that this record is valid to."
        str configuration "Description of any shielding or configuration/setup of the instrumentation."
        str control_schedule "Description of schedule for calibrations or verification of instrument."
        str maintenance_schedule "A description (and schedule) of maintenance that is routinely performed on an instrument."
        dict links "Link(s) to further information on deployment."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    DEPLOYMENT_APPLICATION_AREA{
        str id "Primary key for this record."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    DEPLOYMENT_LOG{
        str id "ID / primary key."
        str author "Author of the log entry."
        datetime datetime "Date and time of the event being logged."
        str description "Description of of the event being logged."
        dict links "Links to further documentation of the logged event."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    DEPLOYMENT_MEDIA{
        str id "Primary key for this record."
        datetime valid_from "Date from which the media is valid."
        datetime valid_to "Date from which the media is no longer valid."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    DEPLOYMENT_PARTY{
        str id "Unique identifier for this record."
        datetime valid_from "Date this record is valid from."
        datetime valid_to "Date this record is valid to."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    EQUIPMENT{
        str id "ID / primary key."
        str description "Description of sensor."
        dict online_resource "Link(s) to further information."
        str specification_link "Link to manufacturers (or other) specification describing the equipment."
        str firmware_version "Firmware version of software installed in sensor."
        str manufacturer "Make, or manufacturer, of sensor."
        str model "Model of sensor."
        str serial_number "Serial number of sensor."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    EQUIPMENT_LOG{
        str id "ID / primary key."
        str author "Author of the log entry."
        datetime datetime "Date and time of the event being logged."
        str description "Description of of the event being logged."
        dict links "Links to further documentation of the logged event."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    EQUIPMENT_MEDIA{
        str id "Primary key for this record."
        datetime valid_from "Date from which the media is valid."
        datetime valid_to "Date from which the media is no longer valid."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    EQUIPMENT_RESPONSIBLE_PARTY{
        str id ""
        datetime valid_from "Date this record is valid from."
        datetime valid_to "Date this record is valid to."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    FEATURE{
        str id "ID / primary key."
        str name "Name of feature."
        str description "Description of feature."
        Geography geometry "Location / geospatial geometry of feature."
        float elevation "Mean elevation of feature above mean sea level."
        dict properties "Array of named values consistent with that defined for the feature type."
        dict links "Link(s) to further information on feature."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    HOST{
        str id "ID / primary key."
        str name "Preferred name of host."
        str description "Description of host."
        dict links "URI to host, e.g. to OSCAR/Surface."
        str wigos_station_identifier "WIGOS station identifier."
        datetime date_established "Date host was first established."
        datetime date_closed "Date host was first established."
        datetime valid_from "Date from which the details for this record are valid."
        datetime valid_to "Date after which the details for this record are no longer valid."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    HOST_AFFILIATION{
        str id "Primary key for this record."
        datetime valid_from "Date from which the details for this record are valid."
        datetime valid_to "Date after which the details for this record are no longer valid."
        str reporting_status "Declared reporting status of an observing facility with respect to a certain program/network affiliation."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    HOST_ALIAS{
        str id "Primary key for this record."
        str alternative_id "Alternative ID by which the host is known."
        str alternative_name "Alternative name by which the host is known."
        str alternative_authority "ID scheme / authority assigning alternative ID."
        datetime valid_from "Date the alternative id/name was used from."
        datetime valid_to "Last date the alternative id/name was used."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    HOST_ENVIRONMENT{
        str id "Primary key for this record."
        datetime valid_from "Date the this record is valid from"
        datetime valid_to "date that this record is valid to"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str _comments "Free text comments on this record, for example description of changes made etc"
    }
    HOST_LOCATION{
        str id "Primary key for this record."
        Geography location "Location of host/station during indicated time period."
        float elevation "Elevation of station above mean sea level in meters."
        datetime valid_from "Date from which the details for this record are valid."
        datetime valid_to "Date after which the details for this record are no longer valid."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    HOST_LOG{
        str id "ID / primary key."
        str author "Author of the log entry."
        datetime datetime "Date and time of the event being logged."
        str description "Description of of the event being logged."
        dict links "Links to further documentation of the logged event."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    HOST_MEDIA{
        str id "Primary key for this record."
        datetime valid_from "Date from which this record is valid."
        datetime valid_to "Date from which this record is no longer valid."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    HOST_RESPONSIBLE_PARTY{
        str id "Unique identifier for this record."
        datetime valid_from "Date this record is valid from."
        datetime valid_to "Date this record is valid to."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    MEDIA{
        str id "ID / primary key."
        str description "Description of the media."
        datetime created "Date the media was created/uploaded."
        str creator "Who uploaded the media. "
        int rights "Digital rights associated with the media."
        str source "Source of the media."
        dict data "TBD"
    }
    OBSERVATION{
        str id "ID / primary key."
        Geography location "Location of observation."
        float elevation "Elevation of observation above mean sea level (in meters)."
        datetime phenomenon_start "Start time of the phenomenon being observed or observing period, if missing assumed instantaneous with time given by phenomenon_end."
        datetime phenomenon_end "End time of the phenomenon being observed or observing period."
        float result_value "The value of the result in float representation."
        str result_uom "Units used to represent the value being observed."
        str result_description "str representation of the result if applicable."
        dict result_quality "JSON representation of the result quality, key / value pairs."
        datetime result_time "Time that the result became available."
        datetime valid_from "Time that the result starts to be valid."
        datetime valid_to "Time after which the result is no longer valid."
        str dataset "Primary dataset that this observation belongs to."
        dict parameter "List of key/ value pairs in dict."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
        str _source_identifier "The original identifier for the record from the data source (if available)."
    }
    REFERENCE_STATIONS{
        str id "ID / primary key for this record."
        datetime valid_from "Date the reference station started as a reference station for this host."
        datetime valid_to "Date the reference station stopped as a reference station for this host."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    RESPONSIBLE_PARTY{
        str id "A value uniquely identifying a party (individual or organization)."
        str individual_name "The name of the organization or the individual."
        str position_name "Role or position of the responsible person."
        str organization_name "Organization/affiliation of the individual/responsible person. In case of an organization, the name property should be used and this property is not to be used."
        dict contact_information "Contact information"
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    SENSOR_CHARACTERISTICS{
        str id "Primary key for this record."
        str observing_method_details "A description of the method of measurement/observation used."
        int measurement_units "The units used in this record."
        float drift_per_unit_time "Intrinsic capability of the measurement/observing method - drift per unit time. Typically a percentage per unit time but could be absolute e.g. 1 degree per year."
        int unit_time "Unit time for drift per unit time (seconds)."
        float valid_min "Minimum observable value by sensor, in units specified by measurement units."
        float valid_max "Maximum observable value by sensor, in units specified by measurement units."
        float specified_absolute_uncertainty "Measurement uncertainty for measurements from this sensor, 2 sigma. Units as per measurement units."
        float specified_relative_uncertainty "Measurement uncertainty for measurements from this sensor, 2 sigma. Units in %, e.g. 20 %."
        dict links "Link(s) to further information."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    SENSOR_OPERATING_STATUS{
        str id "Primary key for this record."
        datetime valid_from "The date from which this status applies."
        datetime valid_to "The date from which this status is no longer valid."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str comments "Free text comments on this record, for example description of changes made etc."
    }
    SOURCE{
        str id "ID / primary key."
        str name "Name of source."
        str description "Description of source type, e.g. file etc."
        dict links "Link(s) to further information on source."
        str processor "Name of processor used to ingest the data."
        dict parameters "Parameters required to access the data from this source (NEED TO CHECK THIS, ENCRYPT?)."
        int _version "Version number of this record."
        datetime _change_date "Date this record was changed."
        str _comments "Free text comments on this record, for example description of changes made etc."
    }
    RECORD{
        str id "A unique identifier of the catalogue record."
        str time "The temporal extent of the resource. Can be null if there is no associated temporal extent."
        str title "A human-readable name given to the resource."
        Geography location "A geometry associated with the resource that is used for discovery. Can be null if there is no associated geometry."
        str created "Date of creation of this record."
        str updated "The most recent date on which the record was changed."
        str resource_type "The nature or genre of the resource. The value should be a code, convenient for filtering records. Where available, a link to the canonical URI of the record type resource will be added to the 'links' property."
        str description "A free-text account of the resource."
        str keywords "The topic or topics of the resource. Typically represented using free-form keywords, tags, key phrases, or classification codes. Semi-colon delimited"
        str language "The natural language used for textual values (e.g. titles, descriptions, etc.) of the resource. ISO 639-1/639-2 codes should be used."
        dict external_ids "An identifier for the resource assigned by an external (to the catalogue) entity."
        dict themes "A knowledge organization system used to classify the resource."
        dict formats "A list of available distributions of the resource."
        dict providers "A list of providers qualified by their role in association to the record."
        str license "A legal document under which the resource is made available. The value should be a code, convenient for filtering the records. Where applicable, the use of the identifiers from the SPDX License List is recommended. If multiple licenses apply, it is recommended to use ''various'.  Where available, links to a URI of each applicable license should be added to the 'links' property."
        str rights "A statement that concerns all rights not addressed by the license such as a copyright statement."
        dict links "A list of links for accessing the resource (e.g. download link, access link) in one of the supported distribution formats and/or links to other resources associated with this resource. Also, a list of links for navigating the API (e.g. prev, next, etc.).  Since the specification requires that at least the self link be present then the min items for this list should be one."
    }
    DEPLOYMENT }o--o|EQUIPMENT: ""
    DEPLOYMENT }o--o|HOST: ""
    DEPLOYMENT }o--o|REFERENCE_SURFACE: ""
    DEPLOYMENT }o--o|COMMUNICATION_METHOD: ""
    DEPLOYMENT }o--||SOURCE_OF_OBSERVATION: ""
    DEPLOYMENT }o--o|EXPOSURE: ""
    DEPLOYMENT }o--o|MEASUREMENT_QUALITY: ""
    DEPLOYMENT }o--o|REPRESENTATIVENESS: ""
    DEPLOYMENT }o--||USER: "Record modified by"
    DEPLOYMENT }o--||STATUS: "Record has status"
    DEPLOYMENT_APPLICATION_AREA }o--||DEPLOYMENT: ""
    DEPLOYMENT_APPLICATION_AREA }o--||APPLICATION_AREA: ""
    DEPLOYMENT_APPLICATION_AREA }o--||USER: "Record modified by"
    DEPLOYMENT_APPLICATION_AREA }o--||STATUS: "Record has status"
    DEPLOYMENT_LOG }o--||DEPLOYMENT: ""
    DEPLOYMENT_LOG }o--||USER: "Record modified by"
    DEPLOYMENT_LOG }o--||STATUS: "Record has status"
    DEPLOYMENT_MEDIA }o--o|DEPLOYMENT: ""
    DEPLOYMENT_MEDIA }o--o|MEDIA: ""
    DEPLOYMENT_MEDIA }o--||USER: "Record modified by"
    DEPLOYMENT_MEDIA }o--||STATUS: "Record has status"
    DEPLOYMENT_PARTY }o--||RESPONSIBLE_PARTY: ""
    DEPLOYMENT_PARTY }o--||ROLE: ""
    DEPLOYMENT_PARTY }o--||DEPLOYMENT: ""
    DEPLOYMENT_PARTY }o--||USER: "Record modified by"
    DEPLOYMENT_PARTY }o--||STATUS: "Record has status"
    EQUIPMENT }o--||EQUIPMENT_TYPE: ""
    EQUIPMENT }o--||USER: "Record modified by"
    EQUIPMENT }o--||STATUS: "Record has status"
    EQUIPMENT_LOG }o--||EQUIPMENT: ""
    EQUIPMENT_LOG }o--||USER: "Record modified by"
    EQUIPMENT_LOG }o--||STATUS: "Record has status"
    EQUIPMENT_MEDIA }o--o|EQUIPMENT: ""
    EQUIPMENT_MEDIA }o--o|MEDIA: ""
    EQUIPMENT_MEDIA }o--||USER: "Record modified by"
    EQUIPMENT_MEDIA }o--||STATUS: "Record has status"
    EQUIPMENT_RESPONSIBLE_PARTY }o--||EQUIPMENT: ""
    EQUIPMENT_RESPONSIBLE_PARTY }o--||RESPONSIBLE_PARTY: ""
    EQUIPMENT_RESPONSIBLE_PARTY }o--||ROLE: ""
    EQUIPMENT_RESPONSIBLE_PARTY }o--||USER: "Record modified by"
    EQUIPMENT_RESPONSIBLE_PARTY }o--||STATUS: "Record has status"
    FEATURE }o--||FEATURE_TYPE: "Is a"
    FEATURE }o--o|FEATURE: "Contained in "
    FEATURE }o--||USER: "Record modified by"
    FEATURE }o--||STATUS: "Record has status"
    HOST }o--o|FACILITY_TYPE: ""
    HOST }o--o|WMO_REGION: ""
    HOST }o--o|TERRITORY: ""
    HOST }o--o|TIME_ZONE: ""
    HOST }o--||USER: "Record modified by"
    HOST }o--||STATUS: "Record has status"
    HOST_AFFILIATION }o--||HOST: ""
    HOST_AFFILIATION }o--o|OBSERVING_PROGRAM: ""
    HOST_AFFILIATION }o--o|HOST_ALIASES: ""
    HOST_AFFILIATION }o--||USER: "Record modified by"
    HOST_AFFILIATION }o--||STATUS: "Record has status"
    HOST_ALIAS }o--||HOST: ""
    HOST_ALIAS }o--||USER: "Record modified by"
    HOST_ALIAS }o--||STATUS: "Record has status"
    HOST_ENVIRONMENT }o--||HOST: ""
    HOST_ENVIRONMENT }o--o|CLIMATE_ZONE: ""
    HOST_ENVIRONMENT }o--o|SURFACE_COVER: ""
    HOST_ENVIRONMENT }o--o|SURFACE_ROUGHNESS: ""
    HOST_ENVIRONMENT }o--o|ALTITUDE: ""
    HOST_ENVIRONMENT }o--o|LOCAL_TOPOGRAPHY: ""
    HOST_ENVIRONMENT }o--o|RELATIVE_ELEVATION: ""
    HOST_ENVIRONMENT }o--o|TOPOGRAPHIC_CONTEXT: ""
    HOST_ENVIRONMENT }o--||USER: "Record modified by"
    HOST_ENVIRONMENT }o--||STATUS: "Record has status"
    HOST_LOCATION }o--||HOST: ""
    HOST_LOCATION }o--o|GEOPOSITIONING_METHOD: ""
    HOST_LOCATION }o--||USER: "Record modified by"
    HOST_LOCATION }o--||STATUS: "Record has status"
    HOST_LOG }o--||HOST: ""
    HOST_LOG }o--||USER: "Record modified by"
    HOST_LOG }o--||STATUS: "Record has status"
    HOST_MEDIA }o--o|HOST: ""
    HOST_MEDIA }o--o|MEDIA: ""
    HOST_MEDIA }o--||USER: "Record modified by"
    HOST_MEDIA }o--||STATUS: "Record has status"
    HOST_RESPONSIBLE_PARTY }o--||RESPONSIBLE_PARTY: ""
    HOST_RESPONSIBLE_PARTY }o--||ROLE: ""
    HOST_RESPONSIBLE_PARTY }o--||HOST: ""
    HOST_RESPONSIBLE_PARTY }o--||USER: "Record modified by"
    HOST_RESPONSIBLE_PARTY }o--||STATUS: "Record has status"
    MEDIA }o--o|MEDIA_TYPE: ""
    OBSERVATION }o--o|OBSERVATION_TYPE: "Is a"
    OBSERVATION }o--||HOST: "Observed at"
    OBSERVATION }o--o|EQUIPMENT: "Observed by"
    OBSERVATION }o--||OBSERVED_PROPERTY: "Estimates / measures"
    OBSERVATION }o--o|OBSERVING_PROCEDURE: "Observed using"
    OBSERVATION }o--o|FEATURE: "Feature of interest"
    OBSERVATION }o--||USER: "Record modified by"
    OBSERVATION }o--||STATUS: "Record has status"
    OBSERVATION }o--||SOURCE: "Comes from"
    REFERENCE_STATIONS }o--o|HOST: ""
    REFERENCE_STATIONS }o--o|HOST: ""
    REFERENCE_STATIONS }o--||USER: "Record modified by"
    REFERENCE_STATIONS }o--||STATUS: "Record has status"
    RESPONSIBLE_PARTY }o--||USER: "Record modified by"
    RESPONSIBLE_PARTY }o--||STATUS: "Record has status"
    SENSOR_CHARACTERISTICS }o--||EQUIPMENT: ""
    SENSOR_CHARACTERISTICS }o--||OBSERVED_PROPERTY: ""
    SENSOR_CHARACTERISTICS }o--||OBSERVING_METHOD: ""
    SENSOR_CHARACTERISTICS }o--||USER: "Record modified by"
    SENSOR_CHARACTERISTICS }o--||STATUS: "Record has status"
    SENSOR_OPERATING_STATUS }o--||DEPLOYMENT: ""
    SENSOR_OPERATING_STATUS }o--||OPERATING_STATUS: ""
    SENSOR_OPERATING_STATUS }o--||USER: "Record modified by"
    SENSOR_OPERATING_STATUS }o--||STATUS: "Record has status"
    SOURCE }o--||SOURCE_TYPE: "Is a"
    SOURCE }o--||USER: "Record modified by"
    SOURCE }o--||STATUS: "Record has status"

