erDiagram
    OBSERVATION_TYPE{
        int id "ID / primary key"
        str name "Short name for observation type"
        str description "Description of observation type"
        dict links "Link(s) to definition of observation type"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    FACILITY_TYPE{
        int id "ID / primary key"
        str name "Short name for feature type"
        str description "Description of feature type"
        dict links "Link(s) to definition of feature type"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    FEATURE_TYPE{
        int id "ID / primary key"
        str name "Short name for feature type"
        str description "Description of feature type"
        dict links "Link(s) to definition of feature type"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    WMO_REGION{
        int id "ID / primary key"
        str name "Short name for feature type"
        str description "Description of feature type"
        dict links "Link(s) to definition of feature type"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    TERRITORY{
        int id "ID / primary key"
        str ISO3c "ID / primary key"
        str name "Short name for feature type"
        str description "Description of feature type"
        dict links "Link(s) to definition of feature type"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    OBSERVED_PROPERTY{
        int id "ID / primary key"
        str short_name "Short name representation of observed property, e.g. 'at'"
        str standard_name "CF standard name (if applicable), e.g. 'air_temperature'"
        str units "Canonical units, e.g. 'Kelvin'"
        str description "Description of observed property"
        dict links "Link(s) to definition / source of observed property"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    OBSERVING_PROCEDURE{
        int id "ID / primary key"
        str name "Name of observing procedure"
        str description "Description of observing procedure"
        dict links "Link(s) to further information"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    STATUS{
        int id "ID / primary key"
        str name "Short name for status"
        str description "Description of the status"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    TIME_ZONE{
        int id "ID / primary key"
        str abbreviation "Abbreviation for time zone"
        str name "Name / description of timezone"
        float offset "Offset from UTC (hours)"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    SOURCE_TYPE{
        str id "ID / primary key"
        str name "Name of source type"
        str description "Description of source type, e.g. file etc"
        str scheme "IANA scheme (if applicable)"
        str links "Links proviing further definition of source type"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    USER{
        str id "ID / primary key"
        str name "Name of user/agent"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    MEDIA{
        str id ""
        str description ""
        datetime created ""
        str creator ""
        int rights ""
        str source ""
        blob data ""
    }
    MEDIA_TYPE{
        int id ""
        int name ""
        str description "Type of media uploaded"
    }
    HOST{
        str id "ID / primary key"
        str name "Preferred name of host"
        str description "Description of host"
        dict links "URI to host, e.g. to OSCAR/Surface"
        Geography location "Location of station"
        float elevation "Elevation of station above mean sea level in meters"
        str wigos_station_identifier "WIGOS station identifier"
        datetime date_established "Date host was first established"
        datetime date_closed "Date host was first established"
        datetime valid_from "Date from which the details for this record are valid"
        datetime valid_to "Date after which the details for this record are no longer valid"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    HOST_ENVIRONMENT{
        str id "Primary key for this record"
        str host_id "Host associated with this record"
        datetime valid_from "Date the this record is valid from"
        datetime valid_to "date that this record is valid to"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    CLIMATE_ZONE{
        int id ""
        str name ""
        str description ""
    }
    SURFACE_COVER{
        int id ""
        str name ""
        str description ""
    }
    SURFACE_ROUGHNESS{
        int id ""
        str name ""
        str description ""
    }
    TOPOGRAPHY{
        int id ""
        str name ""
        str description ""
    }
    SEASON{
        int id ""
        str name ""
        str description ""
    }
    HOST_AFFILIATION{
        str id "Primary key for this record"
        datetime valid_from "Date from which the details for this record are valid"
        datetime valid_to "Date after which the details for this record are no longer valid"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    PROGRAMME{
        int id ""
        str name ""
        str description ""
    }
    HOST_ALIAS{
        str id "Primary key for this record"
        str alternative_id "Alternative ID by which the host is known"
        str alternative_name "Alternative name by which the host is known"
        datetime valid_from "Date the alternative id/name was used from"
        datetime valid_to "Date the alternative id/name was used to"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    HOST_RESPONSIBLE_PARTY{
        int id ""
        str description "Description of role with this association. Note: this will be changed to a code table"
    }
    HOST_MEDIA{
        str id "Primary key for this record"
        datetime valid_from ""
        datetime valid_to ""
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    OBSERVER{
        str id "ID / primary key"
        str name "Name of sensor"
        str description "Description of sensor"
        dict links "Link(s) to further information"
        Geography location "Location of observer"
        float elevation "Elevation of observer above mean sea level"
        str manufacturer "Make, or manufacturer, of sensor"
        str model "Model of sensor"
        str serial_number "Serial number of sensor"
        str firmware_version "Firmware version of software installed in sensor"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    CONTROL_SCHEDULE{
        int id ""
        int name ""
        str description "Description of control schedule"
    }
    OBSERVER_CHARACTERISTICS{
        str id "Primary key for this record"
        int measurement_units "The units used in this record"
        float drift_per_unit_time "Sensor drift per unit time, units specified by measurement units, unit time by unit time"
        int unit_time "Unit time for drift per unit time (seconds)"
        float valid_min "Minimum observable value by sensor, in units specificed by measurement units"
        float valid_max "Maximum observable value by sensor, in units specificed by measurement units"
        float measurement_uncertainty "Measurement uncertainty for measurements from this sensor, 2 sigma. Units as per measuremenet units"
        float measurement_accuracy "Measurement accuracy (trueness) for measurements from this sensor, 2 sigma. Units as per measuremenet units"
        float measurement_repeatability "Measurement repeatability (precision) for measurements from this sensor, 2 sigma. Units as per measuremenet units"
        float measurement_resolution "Minimum change detectable for measurements from this sensor. Units as per measurement units"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    OBSERVING_METHOD{
        int id ""
        int name ""
        str description "Description of observing method"
    }
    OBSERVER_RESPONSIBLE_PARTY{
        int id ""
        str description "Description of role with this association. Note: this will be changed to a code table"
    }
    OBSERVER_MEDIA{
        str id "Primary key for this record"
        datetime valid_from ""
        datetime valid_to ""
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    COLLECTION{
        str id "ID / primary key"
        str name "Name of collection"
        dict links "Link(s) to further information on collection"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    FEATURE{
        str id "ID / primary key"
        str name "Name of feature"
        str description "Description of feature"
        dict links "Link(s) to further information on feature"
        Geography geometry ""
        float elevation "Meam elevation of feature above mean sea level"
        dict properties "Array of named values consistent with that defined for the feature type"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    SOURCE{
        str id "ID / primary key"
        str name "Name of source"
        str description "Description of source type, e.g. file etc"
        dict links "Link(s) to further information on source"
        str processor "Name of processor used to ingest the data"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    OBSERVATION{
        str id "ID / primary key"
        Geography location "Location of observation"
        float elevation "Elevation of observation above mean sea level (in meters)"
        datetime phenomenon_start "Start time of the phenomenon being observed or observing period, if missing assumed instantaneous with time given by phenomenon_end"
        datetime phenomenon_end "End time of the phenomenon being observed or observing period"
        float result_value "The value of the result in float representation"
        str result_uom "Units used to represent the value being observed"
        str result_description "str representation of the result if applicable"
        dict result_quality "JSON representation of the result quality, key / value pairs"
        datetime result_time "Time that the result became available"
        datetime valid_from "Time that the result starts to be valid"
        datetime valid_to "Time after which the result is no longer valid"
        dict parameter "List of key/ value pairs in dict"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
        int _source_identifier "The original identifier for the record from the data source"
    }
    DEPLOYMENT{
        str id "Unique ID / primary key for deployment"
        datetime valid_from ""
        datetime valid_to ""
        float installation_height "Installation height above reference surface (in meters)"
        str configuration "Textual description of sensor installation and configuration"
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    MAINTENANCE_SCHEDULE{
        int id ""
        int name ""
        str description "Description of maintenance schedule"
    }
    EXPOSURE{
        int id ""
        int name ""
        str description "Description of sensor exposure according to WMO-No. 8"
    }
    REFERENCE_SURFACE{
        int id ""
        int name ""
        str description "Description of reference surface"
    }
    DEPLOYMENT_MEDIA{
        str id "Primary key for this record"
        datetime valid_from ""
        datetime valid_to ""
        int _version "Version number of this record"
        datetime _change_date "Date this record was changed"
        str comments "Free text comments on this record, for example description of changes made etc"
    }
    OBSERVATION_TYPE }o--||USER: "Record modified by"
    OBSERVATION_TYPE }o--||STATUS: "Record has status"
    FACILITY_TYPE }o--||USER: "Record modified by"
    FACILITY_TYPE }o--||STATUS: "Record has status"
    FEATURE_TYPE }o--||USER: "Record modified by"
    FEATURE_TYPE }o--||STATUS: "Record has status"
    WMO_REGION }o--||USER: "Record modified by"
    WMO_REGION }o--||STATUS: "Record has status"
    TERRITORY }o--o|WMO_REGION: ""
    TERRITORY }o--||USER: "Record modified by"
    TERRITORY }o--||STATUS: "Record has status"
    OBSERVED_PROPERTY }o--||USER: "Record modified by"
    OBSERVED_PROPERTY }o--||STATUS: "Record has status"
    OBSERVING_PROCEDURE }o--||USER: "Record modified by"
    OBSERVING_PROCEDURE }o--||STATUS: "Record has status"
    STATUS }o--||USER: "Record modified by"
    STATUS }o--||STATUS: "Record has status"
    TIME_ZONE }o--||USER: "Record modified by"
    TIME_ZONE }o--||STATUS: "Record has status"
    SOURCE_TYPE }o--||USER: "Record modified by"
    SOURCE_TYPE }o--||STATUS: "Record has status"
    USER }o--||USER: "Record modified by"
    USER }o--||STATUS: "Record has status"
    MEDIA }o--o|MEDIA_TYPE: ""
    HOST }o--o|FACILITY_TYPE: ""
    HOST }o--o|WMO_REGION: ""
    HOST }o--o|TERRITORY: ""
    HOST }o--o|TIME_ZONE: ""
    HOST }o--||USER: "Record modified by"
    HOST }o--||STATUS: "Record has status"
    HOST_ENVIRONMENT }o--o|CLIMATE_ZONE: ""
    HOST_ENVIRONMENT }o--o|SURFACE_COVER: ""
    HOST_ENVIRONMENT }o--o|SURFACE_ROUGHNESS: ""
    HOST_ENVIRONMENT }o--o|TOPOGRAPHY: ""
    HOST_ENVIRONMENT }o--o|SEASON: ""
    HOST_ENVIRONMENT }o--||USER: "Record modified by"
    HOST_ENVIRONMENT }o--||STATUS: "Record has status"
    HOST_AFFILIATION }o--||HOST: ""
    HOST_AFFILIATION }o--o|PROGRAMME: ""
    HOST_AFFILIATION }o--||USER: "Record modified by"
    HOST_AFFILIATION }o--||STATUS: "Record has status"
    HOST_ALIAS }o--||HOST: ""
    HOST_ALIAS }o--||USER: "Record modified by"
    HOST_ALIAS }o--||STATUS: "Record has status"
    HOST_RESPONSIBLE_PARTY }o--o|USER: ""
    HOST_MEDIA }o--o|HOST: ""
    HOST_MEDIA }o--o|MEDIA: ""
    HOST_MEDIA }o--||USER: "Record modified by"
    HOST_MEDIA }o--||STATUS: "Record has status"
    OBSERVER }o--o|CONTROL_SCHEDULE: ""
    OBSERVER }o--||USER: "Record modified by"
    OBSERVER }o--||STATUS: "Record has status"
    OBSERVER_CHARACTERISTICS }o--||OBSERVER: ""
    OBSERVER_CHARACTERISTICS }o--o|OBSERVED_PROPERTY: ""
    OBSERVER_CHARACTERISTICS }o--o|OBSERVING_METHOD: ""
    OBSERVER_CHARACTERISTICS }o--||USER: "Record modified by"
    OBSERVER_CHARACTERISTICS }o--||STATUS: "Record has status"
    OBSERVER_RESPONSIBLE_PARTY }o--o|USER: ""
    OBSERVER_MEDIA }o--o|OBSERVER: ""
    OBSERVER_MEDIA }o--o|MEDIA: ""
    OBSERVER_MEDIA }o--||USER: "Record modified by"
    OBSERVER_MEDIA }o--||STATUS: "Record has status"
    COLLECTION }o--||USER: "Record modified by"
    COLLECTION }o--||STATUS: "Record has status"
    FEATURE }o--||FEATURE_TYPE: "Is a"
    FEATURE }o--o|FEATURE: "Contained in "
    FEATURE }o--||USER: "Record modified by"
    FEATURE }o--||STATUS: "Record has status"
    SOURCE }o--||SOURCE_TYPE: "Is a"
    SOURCE }o--||USER: "Record modified by"
    SOURCE }o--||STATUS: "Record has status"
    OBSERVATION }o--o|OBSERVATION_TYPE: "Is a"
    OBSERVATION }o--||HOST: "Observed at"
    OBSERVATION }o--o|OBSERVER: "Observed by"
    OBSERVATION }o--||OBSERVED_PROPERTY: "Estimates / measures"
    OBSERVATION }o--o|OBSERVING_PROCEDURE: "Observed using"
    OBSERVATION }o--o|COLLECTION: "Belongs to"
    OBSERVATION }o--o|FEATURE: "Feature of interest"
    OBSERVATION }o--||USER: "Record modified by"
    OBSERVATION }o--||STATUS: "Record has status"
    OBSERVATION }o--||SOURCE: "Comes from"
    DEPLOYMENT }o--o|HOST: ""
    DEPLOYMENT }o--o|OBSERVER: ""
    DEPLOYMENT }o--o|REFERENCE_SURFACE: ""
    DEPLOYMENT }o--o|EXPOSURE: ""
    DEPLOYMENT }o--o|MAINTENANCE_SCHEDULE: ""
    DEPLOYMENT }o--||USER: "Record modified by"
    DEPLOYMENT }o--||STATUS: "Record has status"
    DEPLOYMENT_MEDIA }o--o|DEPLOYMENT: ""
    DEPLOYMENT_MEDIA }o--o|MEDIA: ""
    DEPLOYMENT_MEDIA }o--||USER: "Record modified by"
    DEPLOYMENT_MEDIA }o--||STATUS: "Record has status"

