@startuml
digraph cdm {
node [color=white]
rankdir=LR;
fontname="Arial";
    observation_type [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">observation_type</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Short name for observation type</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of observation type</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">Link(s) to definition of observation type</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    facility_type [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">facility_type</TD><TD COLSPAN="3" BGCOLOR="lightgray">WMDS facility type, type of observing facility</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Short name for feature type</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of feature type</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">Link(s) to definition of feature type</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    feature_type [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">feature_type</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Short name for feature type</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of feature type</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">Link(s) to definition of feature type</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    wmo_region [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">wmo_region</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Short name for feature type</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of feature type</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">Link(s) to definition of feature type</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    territory [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">territory</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="ISO3cL">ISO3c</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="ISO3cR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Short name for feature type</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of feature type</TD></TR>
        <TR><TD PORT="wmo_region_idL">wmo_region_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="wmo_region_idR">WMO region that represents the territory</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">Link(s) to definition of feature type</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    observed_property [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">observed_property</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="short_nameL">short_name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="short_nameR">Short name representation of observed property, e.g. 'at'</TD></TR>
        <TR><TD PORT="standard_nameL">standard_name</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="standard_nameR">CF standard name (if applicable), e.g. 'air_temperature'</TD></TR>
        <TR><TD PORT="unitsL">units</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="unitsR">Canonical units, e.g. 'Kelvin'</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of observed property</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">Link(s) to definition / source of observed property</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    observing_procedure [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">observing_procedure</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Name of observing procedure</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of observing procedure</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">Link(s) to further information</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    status [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">status</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Short name for status</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of the status</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    time_zone [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">time_zone</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="abbreviationL">abbreviation</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="abbreviationR">Abbreviation for time zone</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Name / description of timezone</TD></TR>
        <TR><TD PORT="offsetL">offset</TD><TD>float</TD><TD>NOT NULL</TD><TD></TD><TD PORT="offsetR">Offset from UTC (hours)</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    source_type [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">source_type</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Name of source type</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of source type, e.g. file etc</TD></TR>
        <TR><TD PORT="schemeL">scheme</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="schemeR">IANA scheme (if applicable)</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="linksR">Links proviing further definition of source type</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    user [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">user</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Name of user/agent</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    media [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">media</TD><TD COLSPAN="3" BGCOLOR="lightgray">store for digital media, e.g. photos, reports, videos, etc</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="media_type_idL">media_type_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="media_type_idR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="descriptionR"></TD></TR>
        <TR><TD PORT="createdL">created</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="createdR"></TD></TR>
        <TR><TD PORT="creatorL">creator</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="creatorR"></TD></TR>
        <TR><TD PORT="rightsL">rights</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="rightsR"></TD></TR>
        <TR><TD PORT="sourceL">source</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="sourceR"></TD></TR>
        <TR><TD PORT="dataL">data</TD><TD>blob</TD><TD></TD><TD></TD><TD PORT="dataR"></TD></TR>
        </TABLE>>]
    media_type [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">media_type</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Type of media uploaded</TD></TR>
        </TABLE>>]
    host [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">host</TD><TD COLSPAN="3" BGCOLOR="lightgray">wmdr.observing_facility</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Preferred name of host</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="descriptionR">Description of host</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">URI to host, e.g. to OSCAR/Surface</TD></TR>
        <TR><TD PORT="locationL">location</TD><TD>Geography</TD><TD></TD><TD></TD><TD PORT="locationR">Location of station</TD></TR>
        <TR><TD PORT="elevationL">elevation</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="elevationR">Elevation of station above mean sea level in meters</TD></TR>
        <TR><TD PORT="wigos_station_identifierL">wigos_station_identifier</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="wigos_station_identifierR">WIGOS station identifier</TD></TR>
        <TR><TD PORT="facility_type_idL">facility_type_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="facility_type_idR">Type of observing facility, fixed land, mobile sea, etc</TD></TR>
        <TR><TD PORT="date_establishedL">date_established</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="date_establishedR">Date host was first established</TD></TR>
        <TR><TD PORT="date_closedL">date_closed</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="date_closedR">Date host was first established</TD></TR>
        <TR><TD PORT="wmo_region_idL">wmo_region_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="wmo_region_idR">WMO region in which the host is located</TD></TR>
        <TR><TD PORT="territory_idL">territory_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="territory_idR">Territory the host is located in</TD></TR>
        <TR><TD PORT="time_zone_idL">time_zone_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="time_zone_idR">Time zone the host is located in</TD></TR>
        <TR><TD PORT="valid_fromL">valid_from</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_fromR">Date from which the details for this record are valid</TD></TR>
        <TR><TD PORT="valid_toL">valid_to</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_toR">Date after which the details for this record are no longer valid</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    host_environment [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">host_environment</TD><TD COLSPAN="3" BGCOLOR="lightgray">Description of the environment at the specified host</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">Primary key for this record</TD></TR>
        <TR><TD PORT="host_idL">host_id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="host_idR">Host associated with this record</TD></TR>
        <TR><TD PORT="climate_zone_idL">climate_zone_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="climate_zone_idR">Climate zone that the associated host is located in</TD></TR>
        <TR><TD PORT="surface_cover_idL">surface_cover_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="surface_cover_idR">Type of sueface cover</TD></TR>
        <TR><TD PORT="surface_roughness_idL">surface_roughness_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="surface_roughness_idR">Typical surface roughness of the site surrounding the host</TD></TR>
        <TR><TD PORT="topography_idL">topography_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="topography_idR">Topography of the environment surrounding the host</TD></TR>
        <TR><TD PORT="season_idL">season_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="season_idR">Season that is applicable to this record (e.g. all, winter, spring, summer, autumn)</TD></TR>
        <TR><TD PORT="valid_fromL">valid_from</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_fromR">Date the this record is valid from</TD></TR>
        <TR><TD PORT="valid_toL">valid_to</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_toR">date that this record is valid to</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    climate_zone [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">climate_zone</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR"></TD></TR>
        </TABLE>>]
    surface_cover [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">surface_cover</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR"></TD></TR>
        </TABLE>>]
    surface_roughness [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">surface_roughness</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR"></TD></TR>
        </TABLE>>]
    topography [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">topography</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR"></TD></TR>
        </TABLE>>]
    season [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">season</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR"></TD></TR>
        </TABLE>>]
    host_affiliation [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">host_affiliation</TD><TD COLSPAN="3" BGCOLOR="lightgray">Which programs this host is affiliated with</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">Primary key for this record</TD></TR>
        <TR><TD PORT="host_idL">host_id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="host_idR">Host described by this record</TD></TR>
        <TR><TD PORT="programme_idL">programme_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="programme_idR">Observing programme that this host is affiliated with</TD></TR>
        <TR><TD PORT="valid_fromL">valid_from</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_fromR">Date from which the details for this record are valid</TD></TR>
        <TR><TD PORT="valid_toL">valid_to</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_toR">Date after which the details for this record are no longer valid</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    programme [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">programme</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR"></TD></TR>
        </TABLE>>]
    host_alias [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">host_alias</TD><TD COLSPAN="3" BGCOLOR="lightgray">table to track known aliases for hosts</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">Primary key for this record</TD></TR>
        <TR><TD PORT="host_idL">host_id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="host_idR">Primary ID by which the host is known</TD></TR>
        <TR><TD PORT="alternative_idL">alternative_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="alternative_idR">Alternative ID by which the host is known</TD></TR>
        <TR><TD PORT="alternative_nameL">alternative_name</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="alternative_nameR">Alternative name by which the host is known</TD></TR>
        <TR><TD PORT="valid_fromL">valid_from</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_fromR">Date the alternative id/name was used from</TD></TR>
        <TR><TD PORT="valid_toL">valid_to</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_toR">Date the alternative id/name was used to</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    host_responsible_party [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">host_responsible_party</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="user_idL">user_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="user_idR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of role with this association. Note: this will be changed to a code table</TD></TR>
        </TABLE>>]
    host_media [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">host_media</TD><TD COLSPAN="3" BGCOLOR="lightgray">Link table between hosts and media</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">Primary key for this record</TD></TR>
        <TR><TD PORT="host_idL">host_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="host_idR"></TD></TR>
        <TR><TD PORT="media_idL">media_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="media_idR"></TD></TR>
        <TR><TD PORT="valid_fromL">valid_from</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_fromR"></TD></TR>
        <TR><TD PORT="valid_toL">valid_to</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_toR"></TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    observer [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">observer</TD><TD COLSPAN="3" BGCOLOR="lightgray">wmdr.equipment</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Name of sensor</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of sensor</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">Link(s) to further information</TD></TR>
        <TR><TD PORT="locationL">location</TD><TD>Geography</TD><TD></TD><TD></TD><TD PORT="locationR">Location of observer</TD></TR>
        <TR><TD PORT="elevationL">elevation</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="elevationR">Elevation of observer above mean sea level</TD></TR>
        <TR><TD PORT="manufacturerL">manufacturer</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="manufacturerR">Make, or manufacturer, of sensor</TD></TR>
        <TR><TD PORT="modelL">model</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="modelR">Model of sensor</TD></TR>
        <TR><TD PORT="serial_numberL">serial_number</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="serial_numberR">Serial number of sensor</TD></TR>
        <TR><TD PORT="firmware_versionL">firmware_version</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="firmware_versionR">Firmware version of software installed in sensor</TD></TR>
        <TR><TD PORT="control_schedule_idL">control_schedule_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="control_schedule_idR">Link to information on calibration schedule and details</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    control_schedule [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">control_schedule</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of control schedule</TD></TR>
        </TABLE>>]
    observer_characteristics [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">observer_characteristics</TD><TD COLSPAN="3" BGCOLOR="lightgray">Table to record sensor specifications</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">Primary key for this record</TD></TR>
        <TR><TD PORT="observer_idL">observer_id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="observer_idR">The observer to which this record applies</TD></TR>
        <TR><TD PORT="observed_property_idL">observed_property_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="observed_property_idR">The observed parameter to which this record applies</TD></TR>
        <TR><TD PORT="observing_method_idL">observing_method_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="observing_method_idR">Primary method/principles by which the sensor makes measurements</TD></TR>
        <TR><TD PORT="measurement_unitsL">measurement_units</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="measurement_unitsR">The units used in this record</TD></TR>
        <TR><TD PORT="drift_per_unit_timeL">drift_per_unit_time</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="drift_per_unit_timeR">Sensor drift per unit time, units specified by measurement units, unit time by unit time</TD></TR>
        <TR><TD PORT="unit_timeL">unit_time</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="unit_timeR">Unit time for drift per unit time (seconds)</TD></TR>
        <TR><TD PORT="valid_minL">valid_min</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="valid_minR">Minimum observable value by sensor, in units specificed by measurement units</TD></TR>
        <TR><TD PORT="valid_maxL">valid_max</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="valid_maxR">Maximum observable value by sensor, in units specificed by measurement units</TD></TR>
        <TR><TD PORT="measurement_uncertaintyL">measurement_uncertainty</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="measurement_uncertaintyR">Measurement uncertainty for measurements from this sensor, 2 sigma. Units as per measuremenet units</TD></TR>
        <TR><TD PORT="measurement_accuracyL">measurement_accuracy</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="measurement_accuracyR">Measurement accuracy (trueness) for measurements from this sensor, 2 sigma. Units as per measuremenet units</TD></TR>
        <TR><TD PORT="measurement_repeatabilityL">measurement_repeatability</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="measurement_repeatabilityR">Measurement repeatability (precision) for measurements from this sensor, 2 sigma. Units as per measuremenet units</TD></TR>
        <TR><TD PORT="measurement_resolutionL">measurement_resolution</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="measurement_resolutionR">Minimum change detectable for measurements from this sensor. Units as per measurement units</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    observing_method [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">observing_method</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of observing method</TD></TR>
        </TABLE>>]
    observer_responsible_party [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">observer_responsible_party</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="user_idL">user_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="user_idR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of role with this association. Note: this will be changed to a code table</TD></TR>
        </TABLE>>]
    observer_media [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">observer_media</TD><TD COLSPAN="3" BGCOLOR="lightgray">Link table between hosts and media</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">Primary key for this record</TD></TR>
        <TR><TD PORT="observer_idL">observer_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="observer_idR"></TD></TR>
        <TR><TD PORT="media_idL">media_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="media_idR"></TD></TR>
        <TR><TD PORT="valid_fromL">valid_from</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_fromR"></TD></TR>
        <TR><TD PORT="valid_toL">valid_to</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_toR"></TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    collection [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">collection</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Name of collection</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">Link(s) to further information on collection</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    feature [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">feature</TD><TD COLSPAN="3" BGCOLOR="lightgray">table to contain definition of different geographic features</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="nameR">Name of feature</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="descriptionR">Description of feature</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">Link(s) to further information on feature</TD></TR>
        <TR><TD PORT="feature_type_idL">feature_type_id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="feature_type_idR">enumerated feature type</TD></TR>
        <TR><TD PORT="geometryL">geometry</TD><TD>Geography</TD><TD>NOT NULL</TD><TD></TD><TD PORT="geometryR"></TD></TR>
        <TR><TD PORT="elevationL">elevation</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="elevationR">Meam elevation of feature above mean sea level</TD></TR>
        <TR><TD PORT="parent_idL">parent_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="parent_idR">Parent feature for this feature if nested</TD></TR>
        <TR><TD PORT="propertiesL">properties</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="propertiesR">Array of named values consistent with that defined for the feature type</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    source [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">source</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="nameR">Name of source</TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of source type, e.g. file etc</TD></TR>
        <TR><TD PORT="source_type_idL">source_type_id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="source_type_idR">The type of source</TD></TR>
        <TR><TD PORT="linksL">links</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="linksR">Link(s) to further information on source</TD></TR>
        <TR><TD PORT="processorL">processor</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="processorR">Name of processor used to ingest the data</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    observation [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">observation</TD><TD COLSPAN="3" BGCOLOR="lightgray">table to store observations</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">ID / primary key</TD></TR>
        <TR><TD PORT="locationL">location</TD><TD>Geography</TD><TD>NOT NULL</TD><TD></TD><TD PORT="locationR">Location of observation</TD></TR>
        <TR><TD PORT="elevationL">elevation</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="elevationR">Elevation of observation above mean sea level (in meters)</TD></TR>
        <TR><TD PORT="observation_type_idL">observation_type_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="observation_type_idR">Type of observation</TD></TR>
        <TR><TD PORT="phenomenon_startL">phenomenon_start</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="phenomenon_startR">Start time of the phenomenon being observed or observing period, if missing assumed instantaneous with time given by phenomenon_end</TD></TR>
        <TR><TD PORT="phenomenon_endL">phenomenon_end</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="phenomenon_endR">End time of the phenomenon being observed or observing period</TD></TR>
        <TR><TD PORT="result_valueL">result_value</TD><TD>float</TD><TD>NOT NULL</TD><TD></TD><TD PORT="result_valueR">The value of the result in float representation</TD></TR>
        <TR><TD PORT="result_uomL">result_uom</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="result_uomR">Units used to represent the value being observed</TD></TR>
        <TR><TD PORT="result_descriptionL">result_description</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="result_descriptionR">str representation of the result if applicable</TD></TR>
        <TR><TD PORT="result_qualityL">result_quality</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="result_qualityR">JSON representation of the result quality, key / value pairs</TD></TR>
        <TR><TD PORT="result_timeL">result_time</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="result_timeR">Time that the result became available</TD></TR>
        <TR><TD PORT="valid_fromL">valid_from</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_fromR">Time that the result starts to be valid</TD></TR>
        <TR><TD PORT="valid_toL">valid_to</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_toR">Time after which the result is no longer valid</TD></TR>
        <TR><TD PORT="host_idL">host_id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="host_idR">Host associated with making the observation, equivalent to OGC OMS 'host'</TD></TR>
        <TR><TD PORT="observer_idL">observer_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="observer_idR">Observer associated with making the observation, equivalent to OGC OMS 'observer'</TD></TR>
        <TR><TD PORT="observed_property_idL">observed_property_id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="observed_property_idR">The phenomenon, or thing, being observed</TD></TR>
        <TR><TD PORT="observing_procedure_idL">observing_procedure_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="observing_procedure_idR">Procedure used to make the observation</TD></TR>
        <TR><TD PORT="collection_idL">collection_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="collection_idR">Primary collection or dataset that this observation belongs to. Note: this is different to the OGC OMS collection concept.</TD></TR>
        <TR><TD PORT="parameterL">parameter</TD><TD>dict</TD><TD></TD><TD></TD><TD PORT="parameterR">List of key/ value pairs in dict</TD></TR>
        <TR><TD PORT="feature_idL">feature_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="feature_idR">Feature of interest that this observation is associated with</TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        <TR><TD PORT="_source_idL">_source_id</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_source_idR">The source of this record</TD></TR>
        <TR><TD PORT="_source_identifierL">_source_identifier</TD><TD>int</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_source_identifierR">The original identifier for the record from the data source</TD></TR>
        </TABLE>>]
    deployment [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">deployment</TD><TD COLSPAN="3" BGCOLOR="lightgray">Table to track deployments of an observer to a host</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">Unique ID / primary key for deployment</TD></TR>
        <TR><TD PORT="host_idL">host_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="host_idR"></TD></TR>
        <TR><TD PORT="observer_idL">observer_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="observer_idR"></TD></TR>
        <TR><TD PORT="valid_fromL">valid_from</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_fromR"></TD></TR>
        <TR><TD PORT="valid_toL">valid_to</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_toR"></TD></TR>
        <TR><TD PORT="installation_heightL">installation_height</TD><TD>float</TD><TD></TD><TD></TD><TD PORT="installation_heightR">Installation height above reference surface (in meters)</TD></TR>
        <TR><TD PORT="reference_surfaceL">reference_surface</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="reference_surfaceR"></TD></TR>
        <TR><TD PORT="exposureL">exposure</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="exposureR"></TD></TR>
        <TR><TD PORT="configurationL">configuration</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="configurationR">Textual description of sensor installation and configuration</TD></TR>
        <TR><TD PORT="maintenance_schedule_idL">maintenance_schedule_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="maintenance_schedule_idR"></TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
    maintenance_schedule [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">maintenance_schedule</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of maintenance schedule</TD></TR>
        </TABLE>>]
    exposure [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">exposure</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of sensor exposure according to WMO-No. 8</TD></TR>
        </TABLE>>]
    reference_surface [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">reference_surface</TD><TD COLSPAN="3" BGCOLOR="lightgray">placeholder</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="idR"></TD></TR>
        <TR><TD PORT="nameL">name</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="nameR"></TD></TR>
        <TR><TD PORT="descriptionL">description</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="descriptionR">Description of reference surface</TD></TR>
        </TABLE>>]
    deployment_media [label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="5" COLOR="BLACK">
        <TR><TD COLSPAN="2" BGCOLOR="lightgray">deployment_media</TD><TD COLSPAN="3" BGCOLOR="lightgray">Link table between hosts and media</TD></TR>
        <TR><TD COLSPAN="1" BGCOLOR="lightgray">Column</TD><TD COLSPAN="1" BGCOLOR="lightgray">Type</TD><TD COLSPAN="1" BGCOLOR="lightgray">Nullable</TD><TD COLSPAN="1" BGCOLOR="lightgray">Default</TD><TD COLSPAN="1" BGCOLOR="lightgray">Comments</TD></TR>
        <TR><TD PORT="idL">id</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="idR">Primary key for this record</TD></TR>
        <TR><TD PORT="deployment_idL">deployment_id</TD><TD>str</TD><TD></TD><TD></TD><TD PORT="deployment_idR"></TD></TR>
        <TR><TD PORT="media_idL">media_id</TD><TD>int</TD><TD></TD><TD></TD><TD PORT="media_idR"></TD></TR>
        <TR><TD PORT="valid_fromL">valid_from</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_fromR"></TD></TR>
        <TR><TD PORT="valid_toL">valid_to</TD><TD>datetime</TD><TD></TD><TD></TD><TD PORT="valid_toR"></TD></TR>
        <TR><TD PORT="_versionL">_version</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_versionR">Version number of this record</TD></TR>
        <TR><TD PORT="_change_dateL">_change_date</TD><TD>datetime</TD><TD>NOT NULL</TD><TD></TD><TD PORT="_change_dateR">Date this record was changed</TD></TR>
        <TR><TD PORT="_user_idL">_user_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_user_idR">Which user/agent last modified this record</TD></TR>
        <TR><TD PORT="_status_idL">_status_id</TD><TD>int</TD><TD>NOT NULL</TD><TD>1</TD><TD PORT="_status_idR">Whether this is the latest version or an archived version of the record</TD></TR>
        <TR><TD PORT="commentsL">comments</TD><TD>str</TD><TD>NOT NULL</TD><TD></TD><TD PORT="commentsR">Free text comments on this record, for example description of changes made etc</TD></TR>
        </TABLE>>]
observation_type:_user_idR -> user:idL
observation_type:_status_idR -> status:idL
facility_type:_user_idR -> user:idL
facility_type:_status_idR -> status:idL
feature_type:_user_idR -> user:idL
feature_type:_status_idR -> status:idL
wmo_region:_user_idR -> user:idL
wmo_region:_status_idR -> status:idL
territory:wmo_region_idR -> wmo_region:idL
territory:_user_idR -> user:idL
territory:_status_idR -> status:idL
observed_property:_user_idR -> user:idL
observed_property:_status_idR -> status:idL
observing_procedure:_user_idR -> user:idL
observing_procedure:_status_idR -> status:idL
status:_user_idR -> user:idL
status:_status_idR -> status:idL
time_zone:_user_idR -> user:idL
time_zone:_status_idR -> status:idL
source_type:_user_idR -> user:idL
source_type:_status_idR -> status:idL
user:_user_idR -> user:idL
user:_status_idR -> status:idL
media:media_type_idR -> media_type:idL
host:facility_type_idR -> facility_type:idL
host:wmo_region_idR -> wmo_region:idL
host:territory_idR -> territory:idL
host:time_zone_idR -> time_zone:idL
host:_user_idR -> user:idL
host:_status_idR -> status:idL
host_environment:climate_zone_idR -> climate_zone:idL
host_environment:surface_cover_idR -> surface_cover:idL
host_environment:surface_roughness_idR -> surface_roughness:idL
host_environment:topography_idR -> topography:idL
host_environment:season_idR -> season:idL
host_environment:_user_idR -> user:idL
host_environment:_status_idR -> status:idL
host_affiliation:host_idR -> host:idL
host_affiliation:programme_idR -> programme:idL
host_affiliation:_user_idR -> user:idL
host_affiliation:_status_idR -> status:idL
host_alias:host_idR -> host:idL
host_alias:_user_idR -> user:idL
host_alias:_status_idR -> status:idL
host_responsible_party:user_idR -> user:idL
host_media:host_idR -> host:idL
host_media:media_idR -> media:idL
host_media:_user_idR -> user:idL
host_media:_status_idR -> status:idL
observer:control_schedule_idR -> control_schedule:idL
observer:_user_idR -> user:idL
observer:_status_idR -> status:idL
observer_characteristics:observer_idR -> observer:idL
observer_characteristics:observed_property_idR -> observed_property:idL
observer_characteristics:observing_method_idR -> observing_method:idL
observer_characteristics:_user_idR -> user:idL
observer_characteristics:_status_idR -> status:idL
observer_responsible_party:user_idR -> user:idL
observer_media:observer_idR -> observer:idL
observer_media:media_idR -> media:idL
observer_media:_user_idR -> user:idL
observer_media:_status_idR -> status:idL
collection:_user_idR -> user:idL
collection:_status_idR -> status:idL
feature:feature_type_idR -> feature_type:idL
feature:parent_idR -> feature:idL
feature:_user_idR -> user:idL
feature:_status_idR -> status:idL
source:source_type_idR -> source_type:idL
source:_user_idR -> user:idL
source:_status_idR -> status:idL
observation:observation_type_idR -> observation_type:idL
observation:host_idR -> host:idL
observation:observer_idR -> observer:idL
observation:observed_property_idR -> observed_property:idL
observation:observing_procedure_idR -> observing_procedure:idL
observation:collection_idR -> collection:idL
observation:feature_idR -> feature:idL
observation:_user_idR -> user:idL
observation:_status_idR -> status:idL
observation:_source_idR -> source:idL
deployment:host_idR -> host:idL
deployment:observer_idR -> observer:idL
deployment:reference_surfaceR -> reference_surface:idL
deployment:exposureR -> exposure:idL
deployment:maintenance_schedule_idR -> maintenance_schedule:idL
deployment:_user_idR -> user:idL
deployment:_status_idR -> status:idL
deployment_media:deployment_idR -> deployment:idL
deployment_media:media_idR -> media:idL
deployment_media:_user_idR -> user:idL
deployment_media:_status_idR -> status:idL
}
@enduml
